# -*- coding: utf-8 -*-
"""
Base de donnees des pays souverains (membres ONU + Vatican, Palestine,
Kosovo, Taiwan). Chaque entree : code ISO2 (pour flagcdn), nom francais,
capitale, difficulte, alias pays, alias capitale.
"""

# (code2, nom_fr, capitale, difficulte, [alias_pays], [alias_capitale])
PAYS = [
    # ---------------- AFRIQUE ----------------
    ("dz", "Algérie", "Alger", "facile", ["Algeria"], ["Algiers", "El Djazair"]),
    ("ao", "Angola", "Luanda", "moyen", [], []),
    ("bj", "Bénin", "Porto-Novo", "difficile", ["Benin"], ["Cotonou"]),
    ("bw", "Botswana", "Gaborone", "difficile", [], []),
    ("bf", "Burkina Faso", "Ouagadougou", "moyen", ["Burkina"], ["Ouaga"]),
    ("bi", "Burundi", "Gitega", "difficile", [], ["Bujumbura"]),
    ("cm", "Cameroun", "Yaoundé", "moyen", ["Cameroon"], []),
    ("cv", "Cap-Vert", "Praia", "difficile", ["Cabo Verde", "Cape Verde"], []),
    ("cf", "République centrafricaine", "Bangui", "difficile", ["Centrafrique", "RCA"], []),
    ("td", "Tchad", "N'Djamena", "moyen", ["Chad"], ["Ndjamena"]),
    ("km", "Comores", "Moroni", "difficile", ["Comoros"], []),
    ("cg", "République du Congo", "Brazzaville", "moyen", ["Congo", "Congo-Brazzaville"], []),
    ("cd", "République démocratique du Congo", "Kinshasa", "moyen", ["RDC", "Congo-Kinshasa", "Congo RDC", "Zaire"], []),
    ("dj", "Djibouti", "Djibouti", "difficile", [], []),
    ("eg", "Égypte", "Le Caire", "facile", ["Egypt"], ["Caire", "Cairo"]),
    ("gq", "Guinée équatoriale", "Malabo", "difficile", ["Equatorial Guinea"], []),
    ("er", "Érythrée", "Asmara", "difficile", ["Eritrea"], []),
    ("sz", "Eswatini", "Mbabane", "difficile", ["Swaziland"], []),
    ("et", "Éthiopie", "Addis-Abeba", "moyen", ["Ethiopia"], ["Addis Abeba", "Addis Ababa"]),
    ("ga", "Gabon", "Libreville", "moyen", [], []),
    ("gm", "Gambie", "Banjul", "difficile", ["Gambia"], []),
    ("gh", "Ghana", "Accra", "moyen", [], []),
    ("gn", "Guinée", "Conakry", "moyen", ["Guinea"], []),
    ("gw", "Guinée-Bissau", "Bissau", "difficile", ["Guinea-Bissau"], []),
    ("ci", "Côte d'Ivoire", "Yamoussoukro", "moyen", ["Ivory Coast", "Cote d'Ivoire"], ["Abidjan"]),
    ("ke", "Kenya", "Nairobi", "facile", [], []),
    ("ls", "Lesotho", "Maseru", "difficile", [], []),
    ("lr", "Liberia", "Monrovia", "moyen", ["Libéria"], []),
    ("ly", "Libye", "Tripoli", "moyen", ["Libya"], []),
    ("mg", "Madagascar", "Antananarivo", "moyen", [], ["Tananarive"]),
    ("mw", "Malawi", "Lilongwe", "difficile", [], []),
    ("ml", "Mali", "Bamako", "moyen", [], []),
    ("mr", "Mauritanie", "Nouakchott", "moyen", ["Mauritania"], []),
    ("mu", "Maurice", "Port-Louis", "moyen", ["Ile Maurice", "Mauritius"], []),
    ("ma", "Maroc", "Rabat", "facile", ["Morocco"], []),
    ("mz", "Mozambique", "Maputo", "moyen", [], []),
    ("na", "Namibie", "Windhoek", "moyen", ["Namibia"], []),
    ("ne", "Niger", "Niamey", "moyen", [], []),
    ("ng", "Nigeria", "Abuja", "moyen", ["Nigéria"], []),
    ("rw", "Rwanda", "Kigali", "moyen", [], []),
    ("st", "Sao Tomé-et-Principe", "São Tomé", "difficile", ["Sao Tome", "Sao Tome-et-Principe"], ["Sao Tome"]),
    ("sn", "Sénégal", "Dakar", "facile", ["Senegal"], []),
    ("sc", "Seychelles", "Victoria", "difficile", [], []),
    ("sl", "Sierra Leone", "Freetown", "difficile", [], []),
    ("so", "Somalie", "Mogadiscio", "moyen", ["Somalia"], ["Mogadishu"]),
    ("za", "Afrique du Sud", "Pretoria", "facile", ["South Africa"], ["Le Cap", "Cape Town"]),
    ("ss", "Soudan du Sud", "Djouba", "difficile", ["South Sudan"], ["Juba"]),
    ("sd", "Soudan", "Khartoum", "moyen", ["Sudan"], []),
    ("tz", "Tanzanie", "Dodoma", "moyen", ["Tanzania"], ["Dar es Salaam"]),
    ("tg", "Togo", "Lomé", "moyen", [], ["Lome"]),
    ("tn", "Tunisie", "Tunis", "facile", ["Tunisia"], []),
    ("ug", "Ouganda", "Kampala", "moyen", ["Uganda"], []),
    ("zm", "Zambie", "Lusaka", "moyen", ["Zambia"], []),
    ("zw", "Zimbabwe", "Harare", "moyen", [], []),

    # ---------------- ASIE ----------------
    ("af", "Afghanistan", "Kaboul", "moyen", [], ["Kabul"]),
    ("am", "Arménie", "Erevan", "moyen", ["Armenia"], ["Yerevan"]),
    ("az", "Azerbaïdjan", "Bakou", "moyen", ["Azerbaijan"], ["Baku"]),
    ("bh", "Bahreïn", "Manama", "difficile", ["Bahrain"], []),
    ("bd", "Bangladesh", "Dacca", "moyen", [], ["Dhaka", "Dacca"]),
    ("bt", "Bhoutan", "Thimphou", "difficile", ["Bhutan"], ["Thimphu"]),
    ("bn", "Brunei", "Bandar Seri Begawan", "difficile", [], []),
    ("kh", "Cambodge", "Phnom Penh", "moyen", ["Cambodia"], []),
    ("cn", "Chine", "Pékin", "facile", ["China"], ["Beijing", "Pekin"]),
    ("cy", "Chypre", "Nicosie", "moyen", ["Cyprus"], ["Nicosia"]),
    ("ge", "Géorgie", "Tbilissi", "moyen", ["Georgia"], ["Tbilisi"]),
    ("in", "Inde", "New Delhi", "facile", ["India"], ["Delhi", "New-Delhi"]),
    ("id", "Indonésie", "Jakarta", "moyen", ["Indonesia"], []),
    ("ir", "Iran", "Téhéran", "facile", [], ["Teheran", "Tehran"]),
    ("iq", "Irak", "Bagdad", "moyen", ["Iraq"], ["Baghdad"]),
    ("jp", "Japon", "Tokyo", "facile", ["Japan"], ["Tokyo"]),
    ("jo", "Jordanie", "Amman", "moyen", ["Jordan"], []),
    ("kz", "Kazakhstan", "Astana", "moyen", [], ["Noursoultan", "Nur-Sultan"]),
    ("kw", "Koweït", "Koweït", "moyen", ["Kuwait"], ["Kuwait"]),
    ("kg", "Kirghizistan", "Bichkek", "difficile", ["Kyrgyzstan"], ["Bishkek"]),
    ("la", "Laos", "Vientiane", "difficile", [], []),
    ("lb", "Liban", "Beyrouth", "moyen", ["Lebanon"], ["Beirut"]),
    ("my", "Malaisie", "Kuala Lumpur", "moyen", ["Malaysia"], []),
    ("mv", "Maldives", "Malé", "moyen", [], ["Male"]),
    ("mn", "Mongolie", "Oulan-Bator", "moyen", ["Mongolia"], ["Oulan Bator", "Ulaanbaatar"]),
    ("mm", "Birmanie", "Naypyidaw", "difficile", ["Myanmar"], ["Rangoun", "Yangon"]),
    ("np", "Népal", "Katmandou", "moyen", ["Nepal"], ["Kathmandu", "Katmandu"]),
    ("kp", "Corée du Nord", "Pyongyang", "moyen", ["North Korea", "Coree du Nord"], []),
    ("om", "Oman", "Mascate", "moyen", [], ["Muscat"]),
    ("pk", "Pakistan", "Islamabad", "moyen", [], []),
    ("ps", "Palestine", "Ramallah", "moyen", ["Palestinian"], ["Jérusalem-Est"]),
    ("ph", "Philippines", "Manille", "moyen", [], ["Manila"]),
    ("qa", "Qatar", "Doha", "moyen", [], []),
    ("sa", "Arabie saoudite", "Riyad", "facile", ["Saudi Arabia", "Arabie Saoudite"], ["Riyadh"]),
    ("sg", "Singapour", "Singapour", "moyen", ["Singapore"], ["Singapore"]),
    ("kr", "Corée du Sud", "Séoul", "facile", ["South Korea", "Coree du Sud", "Corée"], ["Seoul"]),
    ("lk", "Sri Lanka", "Colombo", "moyen", [], ["Sri Jayawardenepura Kotte"]),
    ("sy", "Syrie", "Damas", "moyen", ["Syria"], ["Damascus"]),
    ("tj", "Tadjikistan", "Douchanbé", "difficile", ["Tajikistan"], ["Dushanbe"]),
    ("th", "Thaïlande", "Bangkok", "facile", ["Thailand"], []),
    ("tl", "Timor oriental", "Dili", "difficile", ["Timor-Leste", "East Timor"], []),
    ("tr", "Turquie", "Ankara", "facile", ["Turkey", "Türkiye"], ["Istanbul"]),
    ("tm", "Turkménistan", "Achgabat", "difficile", ["Turkmenistan"], ["Ashgabat"]),
    ("ae", "Émirats arabes unis", "Abou Dabi", "moyen", ["Emirats arabes unis", "UAE", "Emirats"], ["Abu Dhabi", "Dubai", "Dubaï"]),
    ("uz", "Ouzbékistan", "Tachkent", "moyen", ["Uzbekistan"], ["Tashkent"]),
    ("vn", "Vietnam", "Hanoï", "moyen", ["Viet Nam"], ["Hanoi", "Ho Chi Minh"]),
    ("ye", "Yémen", "Sanaa", "moyen", ["Yemen"], ["Sana'a"]),
    ("tw", "Taïwan", "Taipei", "moyen", ["Taiwan"], ["Taïpei"]),

    # ---------------- EUROPE ----------------
    ("al", "Albanie", "Tirana", "moyen", ["Albania"], []),
    ("ad", "Andorre", "Andorre-la-Vieille", "difficile", ["Andorra"], ["Andorre la Vieille"]),
    ("at", "Autriche", "Vienne", "facile", ["Austria"], ["Vienna", "Wien"]),
    ("by", "Biélorussie", "Minsk", "moyen", ["Belarus", "Bielorussie"], []),
    ("be", "Belgique", "Bruxelles", "facile", ["Belgium"], ["Brussels"]),
    ("ba", "Bosnie-Herzégovine", "Sarajevo", "moyen", ["Bosnie", "Bosnia"], []),
    ("bg", "Bulgarie", "Sofia", "moyen", ["Bulgaria"], []),
    ("hr", "Croatie", "Zagreb", "moyen", ["Croatia"], []),
    ("cz", "Tchéquie", "Prague", "facile", ["République tchèque", "Republique tcheque", "Czech Republic", "Czechia"], []),
    ("dk", "Danemark", "Copenhague", "facile", ["Denmark"], ["Copenhagen"]),
    ("ee", "Estonie", "Tallinn", "moyen", ["Estonia"], []),
    ("fi", "Finlande", "Helsinki", "facile", ["Finland"], []),
    ("fr", "France", "Paris", "facile", [], []),
    ("de", "Allemagne", "Berlin", "facile", ["Germany"], []),
    ("gr", "Grèce", "Athènes", "facile", ["Greece"], ["Athenes", "Athens"]),
    ("hu", "Hongrie", "Budapest", "moyen", ["Hungary"], []),
    ("is", "Islande", "Reykjavik", "moyen", ["Iceland"], ["Reykjavík"]),
    ("ie", "Irlande", "Dublin", "facile", ["Ireland"], []),
    ("it", "Italie", "Rome", "facile", ["Italy"], []),
    ("xk", "Kosovo", "Pristina", "difficile", [], ["Prishtina"]),
    ("lv", "Lettonie", "Riga", "moyen", ["Latvia"], []),
    ("li", "Liechtenstein", "Vaduz", "difficile", [], []),
    ("lt", "Lituanie", "Vilnius", "moyen", ["Lithuania"], []),
    ("lu", "Luxembourg", "Luxembourg", "moyen", [], []),
    ("mt", "Malte", "La Valette", "moyen", ["Malta"], ["Valette", "Valletta"]),
    ("md", "Moldavie", "Chisinau", "difficile", ["Moldova", "Moldova"], ["Chișinău", "Kichinev"]),
    ("mc", "Monaco", "Monaco", "moyen", [], []),
    ("me", "Monténégro", "Podgorica", "difficile", ["Montenegro"], []),
    ("nl", "Pays-Bas", "Amsterdam", "facile", ["Netherlands", "Hollande", "Holland"], ["La Haye"]),
    ("mk", "Macédoine du Nord", "Skopje", "difficile", ["Macedoine", "North Macedonia", "Macédoine"], []),
    ("no", "Norvège", "Oslo", "facile", ["Norway"], []),
    ("pl", "Pologne", "Varsovie", "facile", ["Poland"], ["Warsaw", "Warszawa"]),
    ("pt", "Portugal", "Lisbonne", "facile", [], ["Lisbon", "Lisboa"]),
    ("ro", "Roumanie", "Bucarest", "moyen", ["Romania"], ["Bucharest"]),
    ("ru", "Russie", "Moscou", "facile", ["Russia"], ["Moscow"]),
    ("sm", "Saint-Marin", "Saint-Marin", "difficile", ["San Marino"], ["San Marino"]),
    ("rs", "Serbie", "Belgrade", "moyen", ["Serbia"], []),
    ("sk", "Slovaquie", "Bratislava", "moyen", ["Slovakia"], []),
    ("si", "Slovénie", "Ljubljana", "moyen", ["Slovenia"], []),
    ("es", "Espagne", "Madrid", "facile", ["Spain"], []),
    ("se", "Suède", "Stockholm", "facile", ["Sweden"], []),
    ("ch", "Suisse", "Berne", "facile", ["Switzerland"], ["Bern", "Zurich"]),
    ("ua", "Ukraine", "Kiev", "facile", [], ["Kyiv"]),
    ("gb", "Royaume-Uni", "Londres", "facile", ["UK", "Angleterre", "Grande-Bretagne", "United Kingdom", "England"], ["London"]),
    ("va", "Vatican", "Vatican", "moyen", ["Saint-Siège", "Vatican City"], ["Cité du Vatican"]),

    # ---------------- AMÉRIQUES ----------------
    ("ag", "Antigua-et-Barbuda", "Saint John's", "difficile", ["Antigua", "Antigua and Barbuda"], ["Saint John", "St John's"]),
    ("ar", "Argentine", "Buenos Aires", "facile", ["Argentina"], []),
    ("bs", "Bahamas", "Nassau", "moyen", [], []),
    ("bb", "Barbade", "Bridgetown", "difficile", ["Barbados"], []),
    ("bz", "Belize", "Belmopan", "difficile", [], []),
    ("bo", "Bolivie", "Sucre", "moyen", ["Bolivia"], ["La Paz"]),
    ("br", "Brésil", "Brasilia", "facile", ["Brazil", "Bresil"], ["Brasília"]),
    ("ca", "Canada", "Ottawa", "facile", [], []),
    ("cl", "Chili", "Santiago", "moyen", ["Chile"], ["Santiago du Chili"]),
    ("co", "Colombie", "Bogota", "moyen", ["Colombia"], ["Bogotá"]),
    ("cr", "Costa Rica", "San José", "moyen", [], ["San Jose"]),
    ("cu", "Cuba", "La Havane", "facile", [], ["Havane", "Havana", "La Habana"]),
    ("dm", "Dominique", "Roseau", "difficile", ["Dominica"], []),
    ("do", "République dominicaine", "Saint-Domingue", "moyen", ["Dominican Republic", "Republique dominicaine"], ["Santo Domingo"]),
    ("ec", "Équateur", "Quito", "moyen", ["Ecuador", "Equateur"], []),
    ("sv", "Salvador", "San Salvador", "moyen", ["El Salvador"], []),
    ("gd", "Grenade", "Saint-Georges", "difficile", ["Grenada"], ["St George's", "Saint George's"]),
    ("gt", "Guatemala", "Guatemala", "moyen", [], ["Guatemala City", "Ciudad de Guatemala"]),
    ("gy", "Guyana", "Georgetown", "difficile", ["Guyane"], []),
    ("ht", "Haïti", "Port-au-Prince", "moyen", ["Haiti"], []),
    ("hn", "Honduras", "Tegucigalpa", "moyen", [], []),
    ("jm", "Jamaïque", "Kingston", "facile", ["Jamaica"], []),
    ("mx", "Mexique", "Mexico", "facile", ["Mexico"], ["Mexico City", "Ciudad de Mexico"]),
    ("ni", "Nicaragua", "Managua", "moyen", [], []),
    ("pa", "Panama", "Panama", "moyen", [], ["Panama City", "Ciudad de Panama"]),
    ("py", "Paraguay", "Asuncion", "moyen", [], ["Asunción"]),
    ("pe", "Pérou", "Lima", "facile", ["Peru", "Perou"], []),
    ("kn", "Saint-Kitts-et-Nevis", "Basseterre", "difficile", ["Saint Kitts", "St Kitts and Nevis"], []),
    ("lc", "Sainte-Lucie", "Castries", "difficile", ["Saint Lucia", "Sainte Lucie"], []),
    ("vc", "Saint-Vincent-et-les-Grenadines", "Kingstown", "difficile", ["Saint Vincent", "St Vincent"], []),
    ("sr", "Suriname", "Paramaribo", "difficile", [], []),
    ("tt", "Trinité-et-Tobago", "Port of Spain", "moyen", ["Trinidad", "Trinite-et-Tobago", "Trinidad and Tobago"], ["Port-d'Espagne"]),
    ("us", "États-Unis", "Washington", "facile", ["USA", "Etats-Unis", "United States", "Amérique", "Amerique"], ["Washington DC"]),
    ("uy", "Uruguay", "Montevideo", "moyen", [], []),
    ("ve", "Venezuela", "Caracas", "moyen", [], []),

    # ---------------- OCÉANIE ----------------
    ("au", "Australie", "Canberra", "facile", ["Australia"], ["Sydney"]),
    ("fj", "Fidji", "Suva", "moyen", ["Fiji"], []),
    ("ki", "Kiribati", "Tarawa", "difficile", [], ["Tarawa-Sud", "South Tarawa"]),
    ("mh", "Îles Marshall", "Majuro", "difficile", ["Marshall", "Iles Marshall", "Marshall Islands"], []),
    ("fm", "Micronésie", "Palikir", "difficile", ["Micronesia"], []),
    ("nr", "Nauru", "Yaren", "difficile", [], []),
    ("nz", "Nouvelle-Zélande", "Wellington", "facile", ["New Zealand", "Nouvelle Zelande"], ["Auckland"]),
    ("pw", "Palaos", "Ngerulmud", "difficile", ["Palau", "Palau"], ["Melekeok"]),
    ("pg", "Papouasie-Nouvelle-Guinée", "Port Moresby", "difficile", ["Papouasie", "Papua New Guinea"], []),
    ("ws", "Samoa", "Apia", "difficile", [], []),
    ("sb", "Îles Salomon", "Honiara", "difficile", ["Salomon", "Iles Salomon", "Solomon Islands"], []),
    ("to", "Tonga", "Nuku'alofa", "difficile", [], ["Nukualofa"]),
    ("tv", "Tuvalu", "Funafuti", "difficile", [], []),
    ("vu", "Vanuatu", "Port-Vila", "difficile", [], ["Port Vila"]),
]

FLAGCDN = "https://flagcdn.com/w320/{}.png"
